<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="demoWSDL" targetNamespace="http://www.example.org/demoWSDL/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.example.org/demoWSDL/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <binding hasEncoding="false" imported="true" name="demoWSDLSOAP" originalBindingStyle="document"/>
        <generatedXSD location="demoWSDL_InlineSchema1.xsd"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
  
  <wsdl:types>
    
          <xsd:schema targetNamespace="http://www.example.org/demoWSDL/" xmlns:ibmSchExtn="http://www.ibm.com/schema/extensions">
<xsd:include schemaLocation="demoWSDL_InlineSchema1.xsd"/>
</xsd:schema>
    </wsdl:types>
  <wsdl:message name="AcctOpeningRequest">
    <wsdl:part element="tns:AcctOpening" name="parameters"/>
  </wsdl:message>
  <wsdl:message name="AcctOpeningResponse">
    <wsdl:part element="tns:AcctOpeningResponse" name="parameters"/>
  </wsdl:message>
  <wsdl:portType name="demoWSDL">
    <wsdl:operation name="AcctOpening">
      <wsdl:input message="tns:AcctOpeningRequest"/>
      <wsdl:output message="tns:AcctOpeningResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="demoWSDLSOAP" type="tns:demoWSDL">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="AcctOpening">
      <soap:operation soapAction="http://www.example.org/demoWSDL/AcctOpening"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="demoWSDL">
    <wsdl:port binding="tns:demoWSDLSOAP" name="demoWSDLSOAP">
      <soap:address location="http://localhost:7801/provider"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>